
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry txtIP;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label2;

	private global::Gtk.Entry txtPort;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btnConnect;

	private global::Gtk.Button btnDisconnect;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ip");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtIP = new global::Gtk.Entry();
		this.txtIP.CanFocus = true;
		this.txtIP.Name = "txtIP";
		this.txtIP.IsEditable = true;
		this.txtIP.InvisibleChar = '•';
		this.hbox1.Add(this.txtIP);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtIP]));
		w2.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Port");
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtPort = new global::Gtk.Entry();
		this.txtPort.CanFocus = true;
		this.txtPort.Name = "txtPort";
		this.txtPort.IsEditable = true;
		this.txtPort.InvisibleChar = '•';
		this.hbox2.Add(this.txtPort);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtPort]));
		w5.Position = 1;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnConnect = new global::Gtk.Button();
		this.btnConnect.CanFocus = true;
		this.btnConnect.Name = "btnConnect";
		this.btnConnect.UseUnderline = true;
		this.btnConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox3.Add(this.btnConnect);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnConnect]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnDisconnect = new global::Gtk.Button();
		this.btnDisconnect.CanFocus = true;
		this.btnDisconnect.Name = "btnDisconnect";
		this.btnDisconnect.UseUnderline = true;
		this.btnDisconnect.Label = global::Mono.Unix.Catalog.GetString("Disconnect");
		this.hbox3.Add(this.btnDisconnect);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnDisconnect]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnConnect.Clicked += new global::System.EventHandler(this.OnBtnConnectClicked);
	}
}
